services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:

    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
