services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge